# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'edaocarios' do
# Uncomment this line if you're using Swift or would like to use dynamic frameworks
#use_frameworks!

# Pods for mmrsios

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'Reachability', '~> 3.2'
pod 'Masonry', '~> 1.0.2'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'  #UITableViewCell自动布局
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SVProgressHUD', '~> 2.1.2'
#pod 'BaiduBCEPlayerFull', '~> 2.0.0'

end
